source = $HOME/.config/hypr/wallust.conf

background = $background
base = $color0
text = $color8
alternate_base = $color1
bright_text = $color15
accent = $color5
accent_secondary = $color6
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
# icon_theme = Papirus-Maia
