# hyprqt6engine configuration
# Generated based on https://wiki.hypr.land/Hypr-Ecosystem/hyprqt6engine/

# Theme settings
[theme]
style=kvantum-dark
font_fixed="JetBrains Mono Nerd Font"
font_fixed_size=13
font="JetBrains Mono Nerd Font"
font_size=13
# color_scheme = "$HOME/.config/hypr/wallust.conf"
icon_theme="Papirus-Dark"
