$background = rgb(161314)
$foreground = rgb(E7FFFC)
$color0 = rgb(413D3F)
$color1 = rgb(BC6850)
$color2 = rgb(947C34)
$color3 = rgb(7A8280)
$color4 = rgb(AC897B)
$color5 = rgb(BEB776)
$color6 = rgb(8CBFB8)
$color7 = rgb(D5F7F2)
$color8 = rgb(95ADA9)
$color9 = rgb(E14F26)
$color10 = rgb(AE8918)
$color11 = rgb(909C99)
$color12 = rgb(E5B7A4)
$color13 = rgb(FDF49D)
$color14 = rgb(BBFFF6)
$color15 = rgb(D5F7F2)
