#!/usr/bin/env bash

fzf="fzf --height 40% --layout reverse --border" 

list_options=$(echo "nvim tmux scripts zshrc ghostty hyprland" | tr " " "\n")

option=$(printf "$list_options" | $fzf)
echo $option


if [[ $option == "nvim" ]]; then
    cd ~/.config/nvim/
    nvim .
elif [[ $option == "tmux" ]]; then
    cd ~/.config/tmux/
    nvim .
elif [[ $option == "scripts" ]]; then
    cd ~/Hiti/dotfiles/scripts/
    nvim .
elif [[ $option == "zshrc" ]]; then
    nvim ~/.zshrc
elif [[ $option == "ghostty" ]]; then
    cd ~/.config/ghostty/
    nvim .
elif [[ $option == "hyprland" ]]; then
    cd ~/.config/hypr/
    nvim .
else echo "Not selected anything..."
fi
