music_directory "/home/hiti/Downloads/Music/"
db_file "/home/hiti/Downloads/Music/musiclibrary.db"
auto_update "yes"
# playlist_directory "~/.local/state/mpd/playlists"
# log_file "~/.local/state/mpd/log"
# pid_file "~/.local/state/mpd/pid"
# state_file "~/.local/state/mpd/state"
# sticker_file "~/.local/state/mpd/sticker.sql"

bind_to_address "/tmp/mpd_socket"
# bind_to_address "localhost"
port "6600"

audio_output {
    type "pipewire"
    name "PipeWire Output"
}

filesystem_charset      "UTF-8"
id3v1_encoding          "UTF-8"
