set -g @foreground "#EDF4F6"
set -g @background "#000007"
set -g @cursor "#B7A490"

set -g @color0 "#000008"
set -g @color1 "#636F62"
set -g @color2 "#856A53"
set -g @color3 "#82707E"
set -g @color4 "#657B89"
set -g @color5 "#468758"
set -g @color6 "#98A8AB"
set -g @color7 "#DDE7E9"
set -g @color8 "#9AA2A3"
set -g @color9 "#697A68"
set -g @color10 "#946C49"
set -g @color11 "#92758C"
set -g @color12 "#64879D"
set -g @color13 "#5EB476"
set -g @color14 "#CBE0E4"
set -g @color15 "#DDE7E9"
