# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Mouse support
set -g mouse on
set -g mode-keys vi
set -g status-keys vi
set-option -g focus-events on
set -g set-clipboard on

# Start windows and panes numbering at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g alternate-screen on

# set true colors
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"

source-file ~/.config/tmux/colors.conf

# window buttons
set -g window-status-format ""
set -g window-status-current-format ""

set -g window-active-style "bg=default"
set -g window-status-style "fg=#{@color2}"
set -g window-status-current-style "fg=#{@color11},bright,bold"
# set -g bell-action "fg=#FF4500"

# Status bar
set -g status-left ""
set -g status-right "#[fg=#{@color6}]Learning Everything... #[fg=#{@color0}, bg=#{@color6}]  #S "
set -g status-style "fg=default,bg=default"
set -g message-style "bg=#{@background}"
set -g mode-style "bg=#{@color4}"


# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind "_" split-window -h -c "#{pane_current_path}"

# Shift+Alt keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window
bind-key n new-window -d -c "#{pane_current_path}"

# Omerxx FLoating term
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind '-n M-p'

# Tmux -Theme
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'Morantron/tmux-fingers'

set -g @tnotify-verbose 'on'
set -g @fingers-pattern-0 "[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)"
bind -n M-f run -b "#{@fingers-cli} start #{pane_id}"

run '~/.config/tmux/plugins/tpm/tpm'
