source-file ~/.config/tmux/colors.conf

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Mouse support
set -g mouse on
setw -g mode-keys vi
set-option -g focus-events on

# Start windows and panes numbering at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set true colors
# set-option -g default-terminal "screen-256color"
set -g default-terminal "${TERM}"
set -ga terminal-overrides ",xterm-256color:RGB"

# Status bar
set -g status-left ""
# set -g status-right "#[fg=#{@my_color_green}]Mastering Everything... #[fg=black, bg=#FFFFFF] #S "
set -g status-right "#[fg=#{@color11}]Learning Everything... #[fg=#{@foreground}, bg=#{@color11}] #S "
set -g status-style bg="#{@background}",fg="#{@foreground}"
set -g message-style bg="#171926",fg=white

# window buttons
set -g window-status-format ""
set -g window-status-current-format ""

set -g window-status-current-style "#{?window_zoomed_flag,fg=#{@color10},fg=#{@color10},nobold}"
set -g window-status-bell-style "fg=#{@color10},nobold"

# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind "_" split-window -h -c "#{pane_current_path}"


# Shift+Alt keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window
bind-key n new-window -d -c "#{pane_current_path}"

bind-key j swap-pane -D
bind-key k swap-pane -U


# Omerxx FLoating term
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind '-n M-p'

# Tmux -Theme
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'
