# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Mouse support
set -g mouse on
setw -g mode-keys vi
set-option -g focus-events on

# Start windows and panes numbering at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set true colors
set -g default-terminal "${TERM}"
set -ga terminal-overrides ",xterm-256color:RGB"

# Status bar
set -g status-left ""
set -g status-style bg="#171926",fg=black,bright
set -g status-right "#[fg=#B8CFCE]#S"

# window buttons
set -g window-status-format ""
set -g window-status-current-format ""

set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind "_" split-window -h -c "#{pane_current_path}"


# Shift+Alt keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window
bind-key n new-window -d -c "#{pane_current_path}"

# Tmux -Theme
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'b0o/tmux-autoreload'

run '~/.tmux/plugins/tpm/tpm'
