require("plugins.colorschemes")
require("plugins.lsp")
require("plugins.extras")
require("plugins.treesitter")
require("plugins.conform")
require("plugins.mini")
require("plugins.snacks")
require("plugins.typst_preview")
require("plugins.blink")
require("plugins.lsp_signature")
require("plugins.my_scripts")
-- require("plugins.minuet")
require("plugins.markdown")
require("plugins.llama_cmp")
